// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlw82dmb_44FsSR_FSCYwp8cDLtYvNtd4',
    appId: '1:462481677284:web:4c4cdf12566aa0ac08c5f1',
    messagingSenderId: '462481677284',
    projectId: 'main-909f0',
    authDomain: 'main-909f0.firebaseapp.com',
    storageBucket: 'main-909f0.firebasestorage.app',
    measurementId: 'G-8T4DS6FWRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWkOonZiVlEr85t9JbJ_EiPssSfgK5bxI',
    appId: '1:462481677284:android:72efa450892dc0f308c5f1',
    messagingSenderId: '462481677284',
    projectId: 'main-909f0',
    storageBucket: 'main-909f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZtGT_61V4C52TGrt6k3D2SFzmdAKuis',
    appId: '1:462481677284:ios:e315e564a00e34a708c5f1',
    messagingSenderId: '462481677284',
    projectId: 'main-909f0',
    storageBucket: 'main-909f0.firebasestorage.app',
    iosBundleId: 'com.movieapps.alvinzanua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpZtGT_61V4C52TGrt6k3D2SFzmdAKuis',
    appId: '1:462481677284:ios:e315e564a00e34a708c5f1',
    messagingSenderId: '462481677284',
    projectId: 'main-909f0',
    storageBucket: 'main-909f0.firebasestorage.app',
    iosBundleId: 'com.movieapps.alvinzanua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlw82dmb_44FsSR_FSCYwp8cDLtYvNtd4',
    appId: '1:462481677284:web:9f1716a021fb8a6608c5f1',
    messagingSenderId: '462481677284',
    projectId: 'main-909f0',
    authDomain: 'main-909f0.firebaseapp.com',
    storageBucket: 'main-909f0.firebasestorage.app',
    measurementId: 'G-FMSPFNC7KS',
  );
}
